import React from "react";
import data from "@/data/dashboard.json";

// Measured results, generated by eval/report_heldout.py from saved runs (numbers only, never email text).
// The live server never runs benchmarks; it only shows these files.

type Count = { n: number; caught: number; named: number };
const pretty = (s: string) => s.replace(/_/g, " ");
const pctText = (n: number, d: number) => (d ? `${Math.round((100 * n) / d)}%` : "–");
const muted = "#64748b";
const th: React.CSSProperties = { textAlign: "left", padding: "0.4rem 0.6rem", color: "#475569", fontWeight: 600, borderBottom: "1px solid #e2e8f0" };
const td: React.CSSProperties = { padding: "0.4rem 0.6rem", borderBottom: "1px solid #f1f5f9", verticalAlign: "middle" };
const section: React.CSSProperties = { fontSize: "1.05rem", fontWeight: 700, color: "#0f172a", margin: "2rem 0 0.5rem" };

// A rate as text plus a thin single-hue meter on a same-ramp track; the text carries the value, the bar only the shape.
function Rate({ n, d }: { n: number; d: number }) {
  if (!d) return <span style={{ color: muted }}>no items</span>;
  return (
    <span title={`${n} of ${d}`} style={{ display: "inline-flex", alignItems: "center", gap: "0.5rem" }}>
      <span style={{ display: "inline-block", width: "5rem", height: "6px", background: "#dbeafe", borderRadius: "4px", overflow: "hidden" }}>
        <span style={{ display: "block", width: `${(100 * n) / d}%`, height: "100%", background: "#2563eb", borderRadius: "4px" }} />
      </span>
      <span style={{ color: "#0f172a", fontVariantNumeric: "tabular-nums" }}>{n}/{d} ({pctText(n, d)})</span>
    </span>
  );
}

function Tile({ value, label, detail }: { value: string; label: string; detail: string }) {
  return (
    <div style={{ flex: "1 1 12rem", background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: "12px", padding: "1rem" }}>
      <div style={{ fontSize: "2rem", fontWeight: 700, color: "#0f172a", fontVariantNumeric: "tabular-nums" }}>{value}</div>
      <div style={{ fontSize: "0.9rem", fontWeight: 600, color: "#334155", marginTop: "0.2rem" }}>{label}</div>
      <div style={{ fontSize: "0.8rem", color: muted, marginTop: "0.3rem" }}>{detail}</div>
    </div>
  );
}

export default function Dashboard() {
  const h = data.heldout;
  const agent = data.agent;
  const adaptive = data.adaptive as null | {
    goals_n: number; rounds: number; succeeded: number; success_rounds: number[]; protected_runs: number; protected_harmful: number;
  };
  const scenarios = data.scenarios as { id: string; title: string; kind: "attack" | "phishing" | "task"; runs: number; unprotected_harmful: number; protected_harmful: number; types_named: string[]; guard_types: string[]; protected_done: number }[];

  return (
    <div>
      <p style={{ margin: "0 0 1rem", fontSize: "0.92rem", color: "#475569" }}>
        Measured on data the firewall was never tuned on: public benchmarks (Microsoft&apos;s LLMail-Inject, agentic boundary pairs, Enron real
        email) plus sets we wrote, which are always shown apart. Run on a laptop with every layer on; full method and per-item IDs
        are in <code>eval/results/</code> on GitHub.
      </p>

      <div style={{ display: "flex", flexWrap: "wrap", gap: "0.75rem" }}>
        <Tile value={pctText(h.public_attacks.caught, h.public_attacks.n)} label="Public held-out attacks caught"
          detail={`${h.public_attacks.caught} of ${h.public_attacks.n} attacks sanitised or quarantined`} />
        <Tile value={pctText(h.real_benign.flagged, h.real_benign.n)} label="Real email wrongly flagged"
          detail={`${h.real_benign.flagged} of ${h.real_benign.n} Enron and LLMail benign emails`} />
        {agent && (
          <Tile value={`${agent.unprotected_harmful} → ${agent.guard_harmful}`} label="Harmful agent actions"
            detail={`Of ${agent.attacks} attack emails, ${agent.unprotected_harmful} made the unprotected agent send data out; with the tool-call guard, ${agent.guard_harmful}.`} />
        )}
        {agent && (
          <Tile value={`${agent.legit_done}/${agent.legit}`} label="Real tasks still done"
            detail="Legitimate send, forward and pay requests completed with full protection on" />
        )}
      </div>

      <h3 style={section}>Detection by attack type</h3>
      <p style={{ margin: "0 0 0.5rem", fontSize: "0.85rem", color: muted }}>
        Caught = sanitised or quarantined. Named = the firewall&apos;s answer names this type. Tool abuse and credential theft are also
        stopped at checkpoint 2 (the tool-call guard), which names them when it blocks an action.
      </p>
      <div style={{ overflowX: "auto" }}>
        <table style={{ borderCollapse: "collapse", fontSize: "0.86rem", width: "100%" }}>
          <thead>
            <tr><th style={th}>Type</th><th style={th}>Public: caught</th><th style={th}>Public: named</th><th style={th}>Ours: caught</th><th style={th}>Ours: named</th></tr>
          </thead>
          <tbody>
            {h.types.map((t: { type: string; public: Count; ours: Count }) => (
              <tr key={t.type}>
                <td style={{ ...td, fontWeight: 600 }}>{pretty(t.type)}</td>
                <td style={td}><Rate n={t.public.caught} d={t.public.n} /></td>
                <td style={td}><Rate n={t.public.named} d={t.public.n} /></td>
                <td style={td}><Rate n={t.ours.caught} d={t.ours.n} /></td>
                <td style={td}><Rate n={t.ours.named} d={t.ours.n} /></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h3 style={section}>By test set</h3>
      <div style={{ overflowX: "auto" }}>
        <table style={{ borderCollapse: "collapse", fontSize: "0.86rem", width: "100%" }}>
          <thead>
            <tr><th style={th}>Set</th><th style={th}>Kind</th><th style={th}>Flagged</th><th style={th}>Attacker&apos;s payload still reaches the AI</th></tr>
          </thead>
          <tbody>
            {h.sets.map((s) => (
              <tr key={s.set}>
                <td style={td}>{s.label}</td>
                <td style={{ ...td, color: s.attack ? "#b91c1c" : "#15803d" }}>{s.attack ? "attack" : "benign"}</td>
                <td style={td}><Rate n={s.flagged} d={s.n} /></td>
                <td style={td}>{s.payload_n ? <Rate n={s.payload_survives} d={s.payload_n} /> : <span style={{ color: muted }}>–</span>}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p style={{ fontSize: "0.82rem", color: muted, margin: "0.5rem 0 0" }}>
        Median {h.median_s} s per item (p90 {h.p90_s} s) · {h.judge_calls} judge calls · {h.sandbox_runs} sandbox runs · {h.errors} errors.
        The boundary-pair benign twins are requests written <em>to an AI</em> (&ldquo;assistant, please …&rdquo;) sent here as email, so many still read as attacks.
      </p>

      {scenarios.length > 0 && (
        <>
          <h3 style={section}>The demo scenarios, measured</h3>
          <table style={{ borderCollapse: "collapse", fontSize: "0.86rem", width: "100%" }}>
            <thead>
              <tr><th style={th}>Scenario</th><th style={th}>Unprotected: attack worked</th><th style={th}>Protected: attack worked</th><th style={th}>Types named (checkpoint 1 / 2)</th></tr>
            </thead>
            <tbody>
              {scenarios.map((s) => (
                <tr key={s.id}>
                  <td style={td}>{s.title}</td>
                  <td style={td}>{s.kind === "task" ? <span style={{ color: muted }}>legitimate task</span> : <Rate n={s.unprotected_harmful} d={s.runs} />}</td>
                  <td style={td}>{s.kind === "task" ? <>task done <Rate n={s.protected_done} d={s.runs} /></> : <Rate n={s.protected_harmful} d={s.runs} />}</td>
                  <td style={td}>{s.types_named.map(pretty).join(", ") || "–"} / {s.guard_types.map(pretty).join(", ") || "–"}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <p style={{ fontSize: "0.82rem", color: muted, margin: "0.5rem 0 0" }}>
            An attack worked if an action carried the attacker&apos;s address; phishing worked if the agent passed the attacker&apos;s link on to the user.
          </p>
        </>
      )}

      {adaptive && (
        <>
          <h3 style={section}>Adaptive attacks: what gets through</h3>
          <p style={{ margin: 0, fontSize: "0.88rem", color: "#334155" }}>
            An attacker model rewrote {adaptive.goals_n} attack emails for up to {adaptive.rounds} rounds each, seeing every time what the firewall
            removed and whether the unprotected agent acted. A round counts only if the email passes the content check <em>and</em> still hijacks the agent.
            {" "}{adaptive.succeeded > 0
              ? <><strong>{adaptive.succeeded} of {adaptive.goals_n}</strong> got there (after {adaptive.success_rounds.join(", ")} rounds). Against the fully protected agent those emails caused <strong>{adaptive.protected_harmful}</strong> harmful actions in {adaptive.protected_runs} runs{adaptive.protected_harmful === 0 ? ": the tool-call guard stopped what the content check missed" : ""}.</>
              : <><strong>None</strong> got there: emails that passed the content check had stopped working as attacks.</>}
            {" "}What no checkpoint stops: plain phishing aimed at the human (&ldquo;re-verify your account at this link&rdquo;) holds no instruction for the AI, so it passes, and the agent repeats it in its summary.
          </p>
        </>
      )}

      <h3 style={section}>Known limits</h3>
      <ul style={{ margin: 0, paddingLeft: "1.2rem", fontSize: "0.88rem", color: "#334155", lineHeight: 1.6 }}>
        <li>No prompt-injection defence is unbreakable: published adaptive attacks beat every defence tested (&ldquo;The Attacker Moves Second&rdquo;, 2025).</li>
        <li>Attacks that every detector scores as clean never reach the LLM judge. The tool-call guard is the backstop, but it only stops actions, not words.</li>
        <li>The guard cannot stop data sent to someone the user really named, or a false summary or phishing link the agent repeats to the user.</li>
        <li>Long documents: detection on text far beyond a classifier&apos;s window is an open research problem; we measure email-length content.</li>
        <li>Our own sets (judge attacks, typed set) are small and written by us; the public sets carry the headline numbers.</li>
      </ul>
    </div>
  );
}
